spring:
  application:
    name: control-plane

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.interrealm.controlplane: DEBUG
    org.springframework.web: INFO