spring:
  application:
    name: control-plane
  datasource:
    url: jdbc:postgresql://localhost:5432/control_plane_db
    username: control_plane_user
    password: control_plane_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    io.interrealm.controlplane: DEBUG
    org.springframework.web: INFO

realmmesh:
  id: ${REALMMESH_ID:550e8400-e29b-41d4-a716-446655440000}
  name: ${REALMMESH_NAME:development-mesh}
  version: ${REALMMESH_VERSION:1.0.0}
  environment: ${REALMMESH_ENVIRONMENT:dev}

api-key:
  key: realm
  bypass-paths:
    - /swagger-ui/**
    - /swagger-ui.html
    - /v3/api-docs/**
    - /v3/api-docs.yaml
    - /api-docs/**
    - /actuator/health
    - /actuator/info
    - /api/v1/mesh/info