openapi: 3.0.3
info:
  title: RealmMesh Control Plane API
  description: API for managing RealmMesh operations and realm orchestration
  version: 1.0.0
  contact:
    name: RealmMesh Team
    url: https://realmmesh.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://control-plane.realmmesh.io/api/v1
    description: Production server

paths:
  /mesh/info:
    get:
      tags:
        - RealmMesh
      summary: Get mesh information
      description: Retrieves information about the current RealmMesh instance
      operationId: getMeshInfo
      responses:
        '200':
          description: Mesh info retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeshInfo'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /router/message:
    post:
      tags:
        - Router
      summary: Route message between realms
      description: Routes a message envelope between realms in the mesh
      operationId: routeMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'interrealm-protocol.yaml#/components/schemas/MessageEnvelope'
      responses:
        '202':
          description: Message accepted for routing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteResponse'
        '400':
          description: Invalid message envelope
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    MeshInfo:
      type: object
      required:
        - uuid
        - name
        - version
        - environment
      properties:
        uuid:
          type: string
          format: uuid
          description: Unique identifier for the mesh instance
        name:
          type: string
          description: Name of the mesh instance
        version:
          type: string
          description: Version of the mesh
        environment:
          type: string
          description: Environment (dev, staging, production)

    RouteResponse:
      type: object
      required:
        - accepted
        - messageId
        - timestamp
      properties:
        accepted:
          type: boolean
          description: Whether the message was accepted for routing
        messageId:
          type: string
          format: uuid
          description: The ID of the accepted message
        timestamp:
          type: string
          format: date-time
          description: Time when the message was accepted
        route:
          type: string
          description: The route the message will take (optional)

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message

    ValidationError:
      type: object
      required:
        - code
        - expected
        - received
        - path
        - message
      properties:
        code:
          type: string
          description: Error code
        expected:
          type: string
          description: Expected value type
        received:
          type: string
          description: Actual received value type
        path:
          type: array
          items:
            type: string
          description: Path to the invalid field
        message:
          type: string
          description: Validation error message

    ValidationErrorResponse:
      type: object
      required:
        - error
        - details
      properties:
        error:
          type: string
          description: General error message
        details:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
          description: Detailed validation errors

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

tags:
  - name: RealmMesh
    description: RealmMesh management operations
  - name: Router
    description: Message routing operations