openapi: 3.0.3
info:
  title: RealmMesh Control Plane API
  description: API for managing RealmMesh operations, capabilities, contracts, and realms
  version: 1.0.0
  contact:
    name: RealmMesh Team
    url: https://realmmesh.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8080/api/v1
    description: Local development server
  - url: https://control-plane.realmmesh.io/api/v1
    description: Production server

paths:

  # ============================================
  # Mesh Info
  # ============================================
  /mesh/info:
    get:
      tags:
        - Mesh
      summary: Get mesh information
      description: Retrieves information about the current RealmMesh instance
      operationId: getMeshInfo
      responses:
        '200':
          description: Mesh info retrieved successfully
          content:
            application/json:
              schema:
                $ref: 'interrealm-protocol.yaml#/components/schemas/MeshInfo'
        '500':
          $ref: '#/components/responses/InternalError'

  # ============================================
  # Message Routing
  # ============================================
  /router/message:
    post:
      tags:
        - Router
      summary: Route message between realms
      description: Routes a message envelope between realms in the mesh
      operationId: routeMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'interrealm-protocol.yaml#/components/schemas/MessageEnvelope'
      responses:
        '202':
          description: Message accepted for routing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RouteResponse'
        '400':
          $ref: '#/components/responses/ValidationError'
        '500':
          $ref: '#/components/responses/InternalError'

 