openapi: 3.0.0
info:
  title: InterRealm Protocol
  version: 1.0.0
  description: |
    Defines the message envelope, core schemas, and capability/contract definitions
    for InterRealm communication. This specification represents the foundational
    protocol used by RealmMesh for distributed message exchange, discovery, and
    routing across Realms.

paths: {}

components:
  schemas:

    # ============================================
    # Core Message Envelope (used by routing API)
    # ============================================
    MessageEnvelope:
      type: object
      required: [messageId, sourceRealm, targetRealm, messageType, timestamp, payload]
      properties:
        messageId:
          type: string
          format: uuid
          description: Unique identifier for this message
        sourceRealm:
          type: string
          description: Identifier of the source realm
          example: "realm://org.cluster.finance"
        targetRealm:
          type: string
          description: Identifier of the target realm
          example: "realm://org.cluster.risk"
        messageType:
          type: string
          enum: [service-request, service-response, event, loop-message]
          description: Type of message being sent
        capabilityRef:
          type: string
          description: Reference to capability (namespace.name/version/resource)
          example: "healthcare.pharmacy/v2.1.0/DrugQuery"
        timestamp:
          type: string
          format: date-time
          description: Time when the message was created
        correlationId:
          type: string
          format: uuid
          description: Correlation ID for request-response tracking (optional)
        headers:
          type: object
          additionalProperties: true
          description: Arbitrary message headers
        payload:
          type: object
          description: Message payload object

    # ============================================
    # Mesh Metadata (used by console and API)
    # ============================================
    MeshInfo:
      type: object
      required: [uuid, name, version, environment]
      properties:
        uuid:
          type: string
          format: uuid
          description: Unique identifier for the RealmMesh instance
        name:
          type: string
          description: Human-readable name of the mesh instance
          example: "enterprise-research-mesh"
        version:
          type: string
          description: Version of the mesh
          example: "1.0.0"
        environment:
          type: string
          description: Environment name (dev, staging, prod)
          example: "development"

    # ============================================
    # Error Schema (common)
    # ============================================
    ErrorDetail:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          description: Machine-readable error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          additionalProperties: true
          description: Additional error context or metadata

    