apiVersion: v1
kind: Namespace
metadata:
  name: genesis
---
apiVersion: v1
kind: Service
metadata:
  name: test-realm
  namespace: genesis
  labels:
    app: test-realm
spec:
  type: ClusterIP
  selector:
    app: test-realm
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-realm
  namespace: genesis
  labels:
    app: test-realm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-realm
  template:
    metadata:
      labels:
        app: test-realm
    spec:
      containers:
      - name: test-realm
        image: docker.io/interrealm/test-realm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
        - name: SERVER_PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3